In [1]:
from database.MongoDBClient import MongoDBClient
from database.Recipe import Recipe
from transformers import AutoTokenizer
from model.model import Chefformer
from config.ModelSettings import ModelSettings
import torch

/Users/michalekb/Documents/GitHub_Personal/chefformer_repo/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/michalekb/Documents/GitHub_Personal/chefformer_repo/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
ModelSettings()

ModelSettings(name='Chefformer', vocab_size=50257, embedding_size=768, max_context_length=512, num_attn_heads=1)

In [3]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
chefformer = Chefformer(tokenizer)


In [4]:
s = """Title: Italian Cream Cake

Ingredients:
- Buttermilk (1 cup)
- Baking soda (1 teaspoon)
- Butter (1/2 cup)
- Shortening (1/2 cup)
- White sugar (2 cups)
- Eggs (5)
- Vanilla extract (1 teaspoon)
- Flaked coconut (1 cup)
- Baking powder (1 teaspoon)
- All-purpose flour (2 cups)
- Cream cheese (8 ounces)
- Butter (1/2 cup)
- Vanilla extract (1 teaspoon)
- Confectioners' sugar (4 cups)
- Light cream (2 tablespoons)
- Chopped walnuts (1/2 cup)
- Sweetened flaked coconut (1 cup)
...

Instructions: Finely grate the zest from 4 of the lemons, then pulse in a mini food processor with 3 tablespoons salt. Squeeze the juice from 2 of the zested lemons into a large bowl; add the lemongrass, olive oil, Sriracha, garlic, fish sauce, brown sugar and 1 teaspoon of the lemon salt. Thinly slice the 2 remaining lemons and add to the bowl.Using kitchen shears, cut through the shrimp shells along the outer curve, leaving the shells on. Remove the veins and rinse the shrimp. Add to the bowl with the lemongrass marinade and toss; cover and refrigerate for 1 hour. Meanwhile, soak 12 to 15 wooden skewers in water.Preheat a grill to medium high. Thread the shrimp onto the skewers. Brush the grill with vegetable oil, then add the lemon slices and grill until they begin to char, turning once, about 2 minutes; transfer to a platter. Stir the mint into the remaining marinade. Add the shrimp skewers to the grill and cook, brushing with the marinade-mint mixture, until the shells begin to char, 2 to 3 minutes per side. Transfer to the platter and sprinkle with the lemon salt to taste."""


s = 'hey how are you'

s = ['hey how', 'are you doing today']

In [5]:
x = tokenizer(s, return_tensors='pt', padding=True, truncation=True, max_length=512)
x['input_ids']

tensor([[20342,   703, 50256, 50256],
        [  533,   345,  1804,  1909]])

In [6]:
embeddings = chefformer.get_embeddings(s)
print(embeddings)
print(embeddings.shape)

tensor([[[ 1.3107,  0.2680,  0.5036,  ..., -0.8320, -0.0170, -0.8597],
         [ 1.6382,  1.6574,  0.6418,  ..., -0.1839, -1.1748,  1.3040],
         [ 2.2366,  0.5333, -0.1260,  ..., -2.5710,  0.0552,  0.3473],
         [ 0.4163,  0.0341, -0.1584,  ..., -1.9265, -1.8974,  2.9538]],

        [[ 0.2781,  0.8924,  0.4302,  ..., -0.1152,  1.3388, -2.6089],
         [ 2.4720,  0.3154,  0.2430,  ...,  0.2069, -1.9308,  1.2749],
         [ 1.0514, -0.7377, -0.0439,  ..., -1.0242,  2.3662, -1.4599],
         [-2.4004, -0.2547, -0.9961,  ...,  0.1721,  0.3143,  0.4929]]],
       grad_fn=<AddBackward0>)
torch.Size([2, 4, 768])


In [7]:
# Test the attention head
attn_output = chefformer.test_attention_head(s)
print(attn_output)
print(attn_output.shape)

tensor([[[-1.8970e-01, -2.3483e-01,  1.0192e+00,  ..., -3.2041e-01,
          -1.4406e-01,  5.3354e-01],
         [-1.4362e-01, -2.8812e-01, -1.1924e-01,  ...,  6.4151e-02,
           2.3038e-01,  6.7085e-02],
         [-1.3207e-01, -2.1637e-01, -2.6068e-01,  ...,  1.0850e-01,
          -1.2325e-01,  7.2677e-04],
         [-1.2331e-01, -6.0520e-02, -1.0089e+00,  ...,  4.0076e-01,
          -2.0545e-01, -3.2228e-01]],

        [[ 2.0997e-01, -3.3625e-01,  3.0315e-01,  ...,  1.4350e+00,
          -4.3398e-01,  1.2214e+00],
         [-2.1666e-01, -4.8512e-01, -1.3374e-01,  ...,  6.3331e-01,
          -2.4757e-01,  4.3898e-01],
         [-8.8211e-02, -2.1788e-01,  5.5244e-02,  ...,  7.1435e-01,
           2.5431e-01,  3.1198e-01],
         [-4.9051e-01,  5.2984e-01, -2.5020e-01,  ...,  4.8360e-01,
           5.8287e-01, -5.9745e-01]]], grad_fn=<BmmBackward0>)
torch.Size([2, 4, 768])
